apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    "codefresh.io/product": "my-product"
  name: test-production-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: resources-prod
    repoURL: https://github.com/danielm-codefresh/guestbook-local.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=true
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
